name: Build and test

on:
  workflow_dispatch:
    inputs:
      run_branch:
        description: 'Branch to run the workflow on'
        required: true
        default: 'master'
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    if: github.event.pull_request.draft == false || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        mcu: [esp32, esp32c3, esp32s3]
        idf: [v5.2, v5.3, v5.4]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Inject build secrets
        run: |
          cat <<EOF > examples/esp32_ex/build_secrets.cmake
          set(SECRETS_MQTT_USER "${{ secrets.MQTT_USER }}" CACHE INTERNAL "")
          set(SECRETS_MQTT_PASS "${{ secrets.MQTT_PASS }}" CACHE INTERNAL "")
          set(SECRETS_MQTT_HOST "${{ secrets.MQTT_HOST }}" CACHE INTERNAL "")
          set(SECRETS_MQTT_PORT "${{ secrets.MQTT_PORT }}" CACHE INTERNAL "")
          set(SECRETS_MQTT_TOPIC "${{ secrets.MQTT_TOPIC }}" CACHE INTERNAL "")
          set(SECRETS_DEVICE_UID "${{ secrets.DEVICE_UID }}" CACHE INTERNAL "")
          EOF

      - name: esp-idf build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: ${{ matrix.idf }}
          target: ${{ matrix.mcu }}
          path: 'examples/esp32_ex'
        
      - name: Select Wokwi diagram for ${{ matrix.mcu }}
        run: cp .wokwi/diagram-${{ matrix.mcu }}.json diagram.json
    
      - name: Test on Wokwi (${{ matrix.mcu }}, IDF ${{ matrix.idf }})
        uses: wokwi/wokwi-ci-action@v1
        with:
          token: ${{ secrets.WOKWI_CLI_TOKEN }}
          timeout: 30000
          expect_text: "publish result='ESP_OK'"
          serial_log_file: wokwi.out

      - name: Upload artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ matrix.mcu }}-${{ matrix.idf }}
          path: |
            examples/esp32_ex/sdkconfig
            examples/esp32_ex/build/flasher_args.json
            wokwi.out
