name: Build and test

on:
  workflow_dispatch:
    inputs:
      run_branch:
        description: 'Branch to run the workflow on'
        required: true
        default: 'master'
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    if: github.event.pull_request.draft == false || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: esp-idf build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.4.1
          target: esp32
          path: 'examples/esp32_ex'

      - name: Test with Wokwi
        uses: wokwi/wokwi-ci-action@v1
        with:
          token: ${{ secrets.WOKWI_CLI_TOKEN }}
          expect_text: 'any web server online'
