
name: Push components to https://components-staging.espressif.com

on:
  push:
    branches:
      - master

jobs:
  upload_components:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      
      - name: Upload components to the component registry
        uses: espressif/upload-components-ci-action@v2
        with:
          components: |
            sensgreen-connector: .
          namespace: "ozanoner"
          api_token: ${{ secrets.IDF_COMPONENT_API_TOKEN }}
          registry_url: https://components-staging.espressif.com
          